=== yuganghu/JAXBDemo/src/main/schemas/redirect.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.waycoolsearch.com/tutorials/search/jaxb/redirect"
	xmlns:tns="http://www.waycoolsearch.com/tutorials/search/jaxb/redirect"
	elementFormDefault="qualified">

	<element name="RedirectRules" type="tns:RedirectRulesType"></element>

	<complexType name="RedirectRulesType">
		<sequence>
			<element name="RedirectRule" type="tns:RedirectRuleType"
				minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="RedirectRuleType">
		<sequence>
			<element name="Queries" type="tns:QueryType"></element>
			<element name="Redirects" type="tns:RedirectType"></element>
		</sequence>
		<attribute name="name" type="string"></attribute>
	</complexType>

	<complexType name="QueryType">
		<sequence>
			<element name="Query" type="string" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	<complexType name="RedirectType">
		<sequence>
			<element name="redirectURL" type="string" minOccurs="1"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>


</schema>

=== yuganghu/JAXBDemo/src/test/resources/redirects.xml
<?xml version="1.0" encoding="UTF-8"?>
<RedirectRules xmlns="http://www.waycoolsearch.com/tutorials/search/jaxb/redirect"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.waycoolsearch.com/tutorials/search/jaxb/redirect ../schemas/redirect.xsd ">
  <RedirectRule name="jaxb redirect">
    <Queries>
      <Query>jaxb</Query>
    </Queries>
    <Redirects>
      <redirectURL>http://tutorials.waycoolsearch.com/java/jaxb.php</redirectURL>
    </Redirects>
  </RedirectRule>
  <RedirectRule name="annotation redirect">
    <Queries>
      <Query>java annotation</Query>
    </Queries>
    <Redirects>
      <redirectURL>http://tutorials.waycoolsearch.com/java/annotation1.php</redirectURL>
    </Redirects>
  </RedirectRule>
</RedirectRules>
